# Generated by Django 5.1.4 on 2026-09-16 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_sample', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-uploaded_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_m', models.IntegerField(db_index=True)),
                ('pressure_bar', models.FloatField()),
                ('temperature_c', models.FloatField()),
                ('anomaly', models.BooleanField(default=False)),
                ('baseline_mean', models.FloatField(blank=True, null=True)),
                ('baseline_std', models.FloatField(blank=True, null=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='readings.run')),
            ],
            options={
                'ordering': ['distance_m'],
                'constraints': [models.UniqueConstraint(fields=('run', 'distance_m'), name='unique_distance_per_run')],
            },
        ),
    ]
